### PR TITLE
Added output of class individuals under has member in ontdoc

### PR DESCRIPTION
**Pull request by adamml**
Under the `ontdoc` profile, individuals of `rdf:type` of the class are now linked from the class definition in HTML and Markdown

Made a small edit to README.RST as well as excludecss=True in the Python statement wasn't working for me.

### CODE REVIEW

**Comment by nicholascar** [comment]
Thanks @adamml! I'll be doing a lot of work on pyLODE next week )project work, not hobby stuff!) so I'll review all this then.

Some new things to appear soon:

* ASCCIIDOC templating for OGC-style outputs (Issue #115)
* linking pyLODE profiles to formally defined profiles (e.g. VocPub to <https://w3id.org/profile/vocpub>
* shape validation as an pre-rendering option
* improvements in the Python code generally
    * eventually moving to RDFlib 6.0.0 when it comes out - a couple of months

**Comment by adamml** [comment]
Thanks for the update @nicholascar 

A bit of background - we're working on an ontology of policies to go with Ireland's National Marine Planning Framework. Some of the stuff I put in the separate profile might, on reflection, be done more introspectively in ontdoc so I may look at that early next week.

The ASCII Doctor might come in handy for documenting  the work on NetCDF-LD using the Binary Array LD ontology which we're prepping for OGC submission.

Looping @jyucsiro and @marqh on that.

**Review by nicholascar — APPROVED** [review]
Approving but un-tested. Will test Monday next week

**Comment by nicholascar** [comment]
@adamml could you send me an example of an NMPF ontology, preferably RDF & HTML (assuming you've already run your own branch of pyLODE on some of your ontologies), just so I have a comparison input & output? for the examples? Thanks.

**Comment by adamml** [comment]
@nicholascar You've got mail...

**Pull request merged**
